# Colors (Hyper)

# Default colors
[colors.primary]
background = '#000000'
foreground = '#ffffff'

[colors.cursor]
text = '#F81CE5'
cursor = '#ffffff'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#fe0100'
green   = '#33ff00'
yellow  = '#feff00'
blue    = '#0066ff'
magenta = '#cc00ff'
cyan    = '#00ffff'
white   = '#d0d0d0'

# Bright colors
[colors.bright]
black   = '#808080'
red     = '#fe0100'
green   = '#33ff00'
yellow  = '#feff00'
blue    = '#0066ff'
magenta = '#cc00ff'
cyan    = '#00ffff'
white   = '#FFFFFF'

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 15

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "BoldItalic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Medium"

[shell]
program = "/usr/bin/fish"

[window]
opacity = 0.9

[window.padding]
x = 5
y = 5
