add_newline = false


format = """
[▒▓](#FFFFFF)\
[   ](bg:#FFFFFF fg:#000000)\
[▓▒▓](#FFFFFF)\
$directory\
[▓▒](#FFFFFF)\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$php\
[▓](#FFFFFF)\
$time\
[▓▒](#FFFFFF)\
\n$character"""

[character]
success_symbol = "[❯](#FFFFFF)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[directory]
style = "bg:#FFFFFF fg:#000000"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#050505"
format = '[[  $time ](bg:#FFFFFF fg:#000000)]($style)'


#Symbols 

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = ""
style = "bg:#FFFFFF fg:#000000"
format = '[[▓](#FFFFFF) $symbol $branch ]($style)'

[git_status]
style = "bg:#FFFFFF fg:#000000"
format = '[($all_status$ahead_behind )]($style)[▓▒](#FFFFFF)'

[golang]
symbol = " "
style = "bg:#FFFFFF fg:#000000"
format = '[ $symbol ]($style)[▓▒](#FFFFFF)'

[guix_shell]
symbol = " "
style = "bg:#FFFFFF fg:#000000"
format = '[ $symbol ]($style)[▓▒](#FFFFFF)'

[haskell]
symbol = " "
style = "bg:#FFFFFF fg:#000000"
format = '[ $symbol ]($style)[▓▒](#FFFFFF)'

[haxe]
symbol = " "
style = "bg:#FFFFFF fg:#000000"
format = '[ $symbol ]($style)[▓▒](#FFFFFF)'

[hg_branch]
symbol = " "
style = "bg:#FFFFFF fg:#000000"
format = '[ $symbol ]($style)[▓▒](#FFFFFF)'

[hostname]
ssh_symbol = " "
style = "bg:#FFFFFF fg:#000000"
format = '[ $symbol ]($style)[▓▒](#FFFFFF)'

[java]
symbol = " "
style = "bg:#FFFFFF fg:#000000"
format = '[ $symbol ]($style)[▓▒](#FFFFFF)'

[julia]
symbol = " "
style = "bg:#FFFFFF fg:#000000"
format = '[ $symbol ]($style)[▓▒](#FFFFFF)'

[lua]
symbol = " "
style = "bg:#FFFFFF fg:#000000"
format = '[ $symbol ]($style)[▓▒](#FFFFFF)'

[memory_usage]
symbol = "󰍛 "
style = "bg:#FFFFFF fg:#000000"
format = '[ $symbol ]($style)[▓▒](#FFFFFF)'

[meson]
symbol = "󰔷 "
style = "bg:#FFFFFF fg:#000000"
format = '[ $symbol ]($style)[▓▒](#FFFFFF)'

[nim]
symbol = "󰆥 "
style = "bg:#FFFFFF fg:#000000"
format = '[ $symbol ]($style)[▓▒](#FFFFFF)'

[nix_shell]
symbol = " "
style = "bg:#FFFFFF fg:#000000"
format = '[ $symbol ]($style)[▓▒](#FFFFFF)'

[nodejs]
symbol = ""
style = "bg:#FFFFFF fg:#000000"
format = '[ $symbol ]($style)[▓▒](#FFFFFF)'

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "
style = "bg:#FFFFFF fg:#000000"
format = '[ $symbol ]($style)[▓▒](#FFFFFF)'

[pijul_channel]
symbol = " "
style = "bg:#FFFFFF fg:#000000"
format = '[ $symbol ]($style)[▓▒](#FFFFFF)'

[python]
symbol = " "
style = "bg:#FFFFFF fg:#000000"
format = '[ $symbol ]($style)[▓▒](#FFFFFF)'

[rlang]
symbol = "󰟔 "
style = "bg:#FFFFFF fg:#000000"
format = '[ $symbol ]($style)[▓▒](#FFFFFF)'

[ruby]
symbol = " "
style = "bg:#FFFFFF fg:#000000"
format = '[ $symbol ]($style)[▓▒](#FFFFFF)'

[rust]
symbol = " "
style = "bg:#FFFFFF fg:#000000"
format = '[ $symbol ]($style)[▓▒](#FFFFFF)'

[scala]
symbol = " "
style = "bg:#FFFFFF fg:#000000"
format = '[ $symbol ]($style)[▓▒](#FFFFFF)'

