# Inserts a blank line between shell prompts
add_newline = false

format = """
[░▒▓](#CBCED3)\
[  ](bg:#CBCED3 fg:#475437)\
[](bg:#B5CC97 fg:#CBCED3)\
$directory\
[](fg:#B5CC97 bg:#667552)\
$git_branch\
$git_status\
[](fg:#667552 bg:#475437)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#475437 bg:#22291a)\
$time\
[ ](fg:#22291a)\
\n$character"""


[directory]
style = "fg:#e3e5e5 bg:#B5CC97"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#22291a"
format = '[[  $time ](fg:#a0a9cb bg:#22291a)]($style)'

#Symbols 

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = ""
style = "bg:#667552"
format = '[[ $symbol $branch ](fg:#B5CC97 bg:#667552)]($style)'

[git_status]
style = "bg:#667552"
format = '[[($all_status$ahead_behind )](fg:#B5CC97 bg:#667552)]($style)'

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

