#!/usr/bin/env bash

window_count=$(hyprctl activeworkspace | grep "windows:" | tr -d "windows: " | tr -d '\t')

cmd_status=$(hyprctl dispatch togglefloating && hyprctl dispatch resizeactive exact 1700 1300 && hyprctl dispatch centerwindow )

if [$cmd_status != "ok"]
then
return 0
fi

case $window_count in
  
  "1")
    hyprctl dispatch centerwindow 
   ;;

  "2")
    hyprctl dispatch movewindow l
    ;;

  "3")
    hyprctl dispatch movewindow r 
    ;;

esac
